export const ATTENDANCE = [
    {
        date: '10/2/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Alonsur' },
            { name: 'Alprazolam' },
            { name: 'Boxcarhobo' },
            { name: 'Bubblygrailz' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dezverly' },
            { name: 'Doruga' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Pwent' },
            { name: 'Serethiel' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '10/22/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Alonsur' },
            { name: 'Alprazolam' },
            { name: 'Boxcarhobo' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dezverly' },
            { name: 'Dress' },
            { name: 'Doruga' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            {
                name: 'Zetsumei'
            }
        ]
    }, {
        date: '10/29/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Alonsur' },
            { name: 'Alprazolam' },
            { name: 'Boxcarhobo' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dezverly' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jarne' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/03/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Boxcarhobo' },
            { name: 'Bubblygrailz' },
            { name: 'Delos' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/06/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dezverly' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Gurkel' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/12/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dezverly' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Kramson' },
            { name: 'Laurah' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/13/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Abraham' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Delos' },
            { name: 'Dezverly' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Gurkel' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Knaz' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproles' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/17/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dondante' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Lumadin' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/19/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Delos' },
            { name: 'Dondante' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Gurkel' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Knaz' },
            { name: 'Kramson' },
            { name: 'Laurah' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Taldia' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/24/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Charmander' },
            { name: 'Delos' },
            { name: 'Dondante' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Grovee' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Kramson' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '11/26/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Harbard' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '12/01/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Fionic' },
            { name: 'Grovee' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Kramson' },
            { name: 'Laurah' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '12/03/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Delos' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Feonier' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Kramson' },
            { name: 'Laurah' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Nitro' },
            { name: 'Pwent' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '12/08/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Delos' },
            { name: 'Doruga' },
            { name: 'Falaris' },
            { name: 'Fellord' },
            { name: 'Fionic' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Helinos' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Laurah' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '12/10/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Daryl' },
            { name: 'Delos' },
            { name: 'Dondante' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Fellord' },
            { name: 'Feonier' },
            { name: 'Fionic' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Helinos' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Kramson' },
            { name: 'Laurah' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Pwent' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Vicca' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '12/11/2019',
        raid: 'Onyxia',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Charmander' },
            { name: 'Delos' },
            { name: 'Dress' },
            { name: 'Dunnrik' },
            { name: 'Falaris' },
            { name: 'Fellord' },
            { name: 'Feonier' },
            { name: 'Fionic' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Gurkel' },
            { name: 'Icescreamer' },
            { name: 'Jarett' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Vicca' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }, {
        date: '12/17/2019',
        raid: 'Molten Core',
        players: [
            { name: 'Abraham' },
            { name: 'Aelari' },
            { name: 'Alonsur' },
            { name: 'Begrungi' },
            { name: 'Bubblygrailz' },
            { name: 'Burningman' },
            { name: 'Daryl' },
            { name: 'Doruga' },
            { name: 'Dress' },
            { name: 'Falaris' },
            { name: 'Fellord' },
            { name: 'Feonier' },
            { name: 'Forcedawg' },
            { name: 'Gried' },
            { name: 'Grovee' },
            { name: 'Helinos' },
            { name: 'Horon' },
            { name: 'Icescreamer' },
            { name: 'Immortal' },
            { name: 'Jarett' },
            { name: 'Jbaum' },
            { name: 'Kelharath' },
            { name: 'Knaz' },
            { name: 'Meowntain' },
            { name: 'Minerva' },
            { name: 'Pwent' },
            { name: 'Quippie' },
            { name: 'Rhonto' },
            { name: 'Roic' },
            { name: 'Selnath' },
            { name: 'Serethiel' },
            { name: 'Sproggle' },
            { name: 'Sproles' },
            { name: 'Taggart' },
            { name: 'Talate' },
            { name: 'Vicca' },
            { name: 'Vick' },
            { name: 'Wander' },
            { name: 'Xinghua' },
            { name: 'Zetsumei' }
        ]
    }
];
