export const BOSS_LOOT = [
    {
        name: 'Lucifron',
        loot: [
            'Arcanist Boots',
            'Cenarion Boots',
            'Choker of Enlightenment',
            'Felheart Gloves',
            'Flamewaker Legplates',
            'Gauntlets of Might',
            'Heavy Dark Iron Ring',
            'Lawbringer Boots',
            'Manastorm Leggings',
            'Ring of Spell Power',
            'Robe of Volatile Power'
        ]
    },
    {
        name: 'Magmadar',
        loot: [
            'Aged Core Leather Gloves',
            'Arcanist Leggings',
            'Cenarion Leggings',
            'Deep Earth Spaulders',
            'Earthshaker',
            'Eskhandar\'s Right Claw',
            'Felheart Pants',
            'Fire Runed Grimoire',
            'Flameguard Gauntlets',
            'Flamewaker Legplates',
            'Formula: Enchant Weapon - Healing Power',
            'Giantstalker\'s Leggings',
            'Lawbringer Legplates',
            'Legplates of Might',
            'Magma Tempered Boots',
            'Mana Igniting Cord',
            'Medallion of Steadfast Might',
            'Nightslayer Pants',
            'Obsidian Edged Blade',
            'Pants of Prophecy',
            'Plans: Elemental Sharpening Stone',
            'Quick Strike Ring',
            'Sabatons of the Flamewalker',
            'Striker\'s Mark',
            'Talisman of Ephemeral Power'
        ]
    },
    {
        name: 'Gehennas',
        loot: [
            'Crimson Shocker',
            'Flamewaker Legplates',
            'Giantstalker\'s Boots',
            'Gloves of Prophecy',
            'Heavy Dark Iron Ring',
            'Lawbringer Gauntlets',
            'Manastorm Leggings',
            'Nightslayer Gloves',
            'Ring of Spell Power',
            'Robe of Volatile Power',
            'Sabatons of Might',
            'Salamander Scale Pants',
            'Sorcerous Dagger',
            'Wristguards of Stability'
        ]
    },
    {
        name: 'Garr',
        loot: [
            'Aged Core Leather Gloves',
            'Arcanist Crown',
            'Aurastone Hammer',
            'Bindings of the Windseeker',
            'Brutality Blade',
            'Cenarion Helm',
            'Circlet of Prophecy',
            'Deep Earth Spaulders',
            'Drillborer Disk',
            'Felheart Horns',
            'Fire Runed Grimoire',
            'Flameguard Gauntlets',
            'Flamewaker Legplates',
            'Giantstalker\'s Helmet',
            'Gutgore Ripper',
            'Helm of Might',
            'Lawbringer Helm',
            'Magma Tempered Boots',
            'Mana Igniting Cord',
            'Nightslayer Cover',
            'Obsidian Edged Blade',
            'Quick Strike Ring',
            'Talisman of Ephemeral Power'
        ]
    },
    {
        name: 'Shazzrah',
        loot: [
            'Arcanist Gloves',
            'Boots of Prophecy',
            'Cenarion Gloves',
            'Crimson Shocker',
            'Felheart Slippers',
            'Giantstalker\'s Gloves',
            'Nightslayer Boots',
            'Ring of Spell Power',
            'Robe of Volatile Power',
            'Sorcerous Dagger'
        ]
    },
    {
        name: 'Geddon',
        loot: [
            'Aged Core Leather Gloves',
            'Arcanist Mantle',
            'Bindings of the Windseeker',
            'Cenarion Spaulders',
            'Felheart Shoulder Pads',
            'Fire Runed Grimoire',
            'Flameguard Gauntlets',
            'Flamewaker Legplates',
            'Lawbringer Spaulders',
            'Magma Tempered Boots',
            'Mana Igniting Cord',
            'Obsidian Edged Blade',
            'Pattern: Core Armor Kit',
            'Plans: Elemental Sharpening Stone',
            'Quick Strike Ring',
            'Schematic: Force Reactive Disk',
            'Seal of the Archmagus',
            'Talisman of Ephemeral Power'
        ]
    },
    {
        name: 'Golemagg',
        loot: [
            'Aged Core Leather Gloves',
            'Arcanist Robes',
            'Azuresong Mageblade',
            'Blastershot Launcher',
            'Breastplate of Might',
            'Cenarion Vestments',
            'Felheart Robes',
            'Fire Runed Grimoire',
            'Flameguard Gauntlets',
            'Flamewaker Legplates',
            'Giantstalker\'s Breastplate',
            'Lawbringer Chestguard',
            'Mana Igniting Cord',
            'Nightslayer Chestpiece',
            'Obsidian Edged Blade',
            'Pattern: Core Armor Kit',
            'Quick Strike Ring',
            'Recipe: Major Rejuvenation Potion',
            'Robes of Prophecy',
            'Staff of Dominance',
            'Talisman of Ephemeral Power'
        ]
    },
    {
        name: 'Harbinger',
        loot: [
            'Crimson Shocker',
            'Flamewaker Legplates',
            'Giantstalker\'s Epaulets',
            'Heavy Dark Iron Ring',
            'Manastorm Leggings',
            'Mantle of Prophecy',
            'Nightslayer Shoulder Pads',
            'Pauldrons of Might',
            'Ring of Spell Power',
            'Salamander Scale Pants',
            'Shadowstrike',
            'Sorcerous Dagger',
            'Wristguards of Stability'
        ]
    },
    {
        name: 'Majordomo',
        loot: [
            'Ancient Petrified Leaf',
            'Cauterizing Band',
            'Core Forged Greaves',
            'Core Hound Tooth',
            'Finkle\'s Lava Dredger',
            'Fireguard Shoulders',
            'Fireproof Cloak',
            'Gloves of the Hypnotic Flame',
            'Sash of Whispered Secrets',
            'The Eye of Divinity',
            'Wild Growth Spaulders',
            'Wristguards of True Flight'
        ]
    },
    {
        name: 'Ragnaros',
        loot: [
            'Band of Accuria',
            'Band of Sulfuras',
            'Bloodfang Pants',
            'Bonereaver\'s Edge',
            'Choker of the Fire Lord',
            'Cloak of the Shrouded Mists',
            'Crown of Destruction',
            'Dragon\'s Blood Cape',
            'Dragonstalker\'s Legguards',
            'Essence of the Pure Flame',
            'Eye of Sulfuras',
            'Judgement Legplates',
            'Leggings of Transcendence',
            'Legplates of Ten Storms',
            'Legplates of Wrath',
            'Malistar\'s Defender',
            'Nemesis Leggings',
            'Netherwind Pants',
            'Onslaught Girdle',
            'Perdition\'s Blade',
            'Shard of the Flame',
            'Spinal Reaper',
            'Stormrage Legguards'
        ]
    }
];
